## Import Libraries

In [1]:
import pandas as pd
import numpy as np

## Define File Path

In [7]:
file_path = "D:/Final Project/data/trail_edge_dataset.xlsx"

excel_file = pd.ExcelFile(file_path)

In [8]:
excel_file.sheet_names

['Product_Information', 'Weekly_Sales', 'External_Features']

## READ REQUIRED SHEETS

In [9]:
product_info = pd.read_excel(file_path, sheet_name='Product_Information')

In [10]:
weekly_sales = pd.read_excel(file_path, sheet_name='Weekly_Sales')

In [11]:
product_info.head()

,Product_ID,Product_Name,Category,Sub_Category,Gender,Color,Launch_Season,Launch_Date,MSRP,Wholesale_Price
0,TE001,Backpack 1,Gear,Backpacks,Women,Blue,Winter,2022-10-19,139,83.21
1,TE002,Backpack 2,Gear,Backpacks,Men,Blue,Spring,2022-01-20,191,114.19
2,TE003,Backpack 3,Gear,Backpacks,Men,Red,Summer,2022-02-21,104,72.57
3,TE004,Pant 4,Apparel,Pants,Unisex,Green,Spring,2022-12-22,149,102.90
4,TE005,Accessorie 5,Gear,Accessories,Women,Green,Spring,2022-04-15,59,37.76

In [ ]:
product_info.shape
product_info.columns
product_info.info()

(25, 10)

In [13]:
product_info.describe(include='all')

,Product_ID,Product_Name,Category,Sub_Category,Gender,Color,Launch_Season,Launch_Date,MSRP,Wholesale_Price
count,25,25,25,25,25,25,25,25,25.000000,25.000000
unique,25,25,3,7,3,6,4,NaN,NaN,NaN
top,TE001,Backpack 1,Gear,T-Shirts,Unisex,Blue,Spring,NaN,NaN,NaN
freq,1,1,10,6,12,5,11,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-14 03:50:24,120.720000,72.743600
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-02 00:00:00,59.000000,32.650000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-03-02 00:00:00,94.000000,55.080000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-17 00:00:00,127.000000,72.570000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-11-05 00:00:00,149.000000,91.410000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-12-22 00:00:00,191.000000,114.190000
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.850055,24.022595

## Data Understanding Product Info

In [14]:
product_info.isnull().sum()

Product_ID         0
Product_Name       0
Category           0
Sub_Category       0
Gender             0
Color              0
Launch_Season      0
Launch_Date        0
MSRP               0
Wholesale_Price    0
dtype: int64

In [15]:
product_info.duplicated().sum()

np.int64(0)

In [16]:
product_info['Product_ID'].nunique()

25

## Check Important Categorical Values

In [17]:
product_info['Category'].unique()

<StringArray>
['Gear', 'Apparel', 'Footwear']
Length: 3, dtype: str

In [18]:
product_info['Sub_Category'].unique()

<StringArray>
[   'Backpacks',        'Pants',  'Accessories',     'T-Shirts',
 'Hiking Boots',      'Jackets',  'Trail Shoes']
Length: 7, dtype: str

In [19]:
product_info['Gender'].unique()

<StringArray>
['Women', 'Men', 'Unisex']
Length: 3, dtype: str

## DATA UNDERSTANDING: WEEKLY_SALES

weekly_sales.head()

In [20]:
weekly_sales.shape

(2600, 7)

In [21]:
weekly_sales.columns

Index(['Week_End_Date', 'Product_ID', 'Qty_Sold', 'Inventory', 'On_Order',
       'Returns', 'Discount'],
      dtype='str')

In [22]:
weekly_sales['Week_End_Date'] = pd.to_datetime(weekly_sales['Week_End_Date'])

In [23]:
weekly_sales.describe(include='all')

,Week_End_Date,Product_ID,Qty_Sold,Inventory,On_Order,Returns,Discount
count,2600,2600,2600.000000,2600.000000,2600.000000,2600.000000,2600.000000
unique,NaN,25,NaN,NaN,NaN,NaN,NaN
top,NaN,TE001,NaN,NaN,NaN,NaN,NaN
freq,NaN,104,NaN,NaN,NaN,NaN,NaN
mean,2024-01-02 12:00:00,NaN,56.454615,397.295769,176.378077,2.305385,9.994231
min,2023-01-07 00:00:00,NaN,14.000000,274.000000,50.000000,0.000000,0.000000
25%,2023-07-06 06:00:00,NaN,33.000000,347.000000,115.000000,1.000000,5.000000
50%,2024-01-02 12:00:00,NaN,53.000000,397.000000,178.000000,2.000000,10.000000
75%,2024-06-30 18:00:00,NaN,76.000000,449.000000,239.000000,3.000000,15.000000
max,2024-12-28 00:00:00,NaN,150.000000,520.000000,300.000000,11.000000,20.000000
std,NaN,NaN,27.501251,60.994836,71.658615,1.740530,7.051313

In [24]:
weekly_sales.isnull().sum()

Week_End_Date    0
Product_ID       0
Qty_Sold         0
Inventory        0
On_Order         0
Returns          0
Discount         0
dtype: int64

In [25]:
weekly_sales.duplicated().sum()

np.int64(0)

In [26]:
weekly_sales['Product_ID'].nunique()

25

In [27]:
weekly_sales['Week_End_Date'].min(), weekly_sales['Week_End_Date'].max()

(Timestamp('2023-01-07 00:00:00'), Timestamp('2024-12-28 00:00:00'))

In [28]:
weekly_sales['Week_End_Date'].nunique()

104

In [29]:
sample_product = weekly_sales['Product_ID'].iloc[0]
weekly_sales[weekly_sales['Product_ID'] == sample_product].head(10)

  Week_End_Date Product_ID  Qty_Sold  Inventory  On_Order  Returns  Discount
0    2023-01-07      TE001        69        504       129        3        20
1    2023-01-14      TE001        73        509       240        2        10
2    2023-01-21      TE001        61        492       189        4         5
3    2023-01-28      TE001        51        483        80        3         5
4    2023-02-04      TE001        69        495       195        2        15
5    2023-02-11      TE001        56        503       135        1        10
6    2023-02-18      TE001        48        473       272        3         5
7    2023-02-25      TE001        58        474       221        1        10
8    2023-03-04      TE001        75        488       288        4        10
9    2023-03-11      TE001        53        470       131        1         0

## LINKING CHECK BETWEEN BOTH DATASETS

In [30]:
products_only_in_info = set(product_info['Product_ID']) - set(weekly_sales['Product_ID'])
products_only_in_sales = set(weekly_sales['Product_ID']) - set(product_info['Product_ID'])

print("Products only in Product_Info:", products_only_in_info)
print("Products only in Weekly_Sales:", products_only_in_sales)

Products only in Product_Info: set()
Products only in Weekly_Sales: set()

In [31]:
print("========== DATA UNDERSTANDING SUMMARY ==========")
print("Product Info Shape:", product_info.shape)
print("Weekly Sales Shape:", weekly_sales.shape)
print("Unique Products in Product Info:", product_info['Product_ID'].nunique())
print("Unique Products in Weekly Sales:", weekly_sales['Product_ID'].nunique())
print("Sales Date Range:", weekly_sales['Week_End_Date'].min(), "to", weekly_sales['Week_End_Date'].max())
print("Total Unique Weeks:", weekly_sales['Week_End_Date'].nunique())

========== DATA UNDERSTANDING SUMMARY ==========
Product Info Shape: (25, 10)
Weekly Sales Shape: (2600, 7)
Unique Products in Product Info: 25
Unique Products in Weekly Sales: 25
Sales Date Range: 2023-01-07 00:00:00 to 2024-12-28 00:00:00
Total Unique Weeks: 104

In [32]:
product_info.head()
product_info['Category'].unique()
product_info['Sub_Category'].unique()
product_info['Gender'].unique()

<StringArray>
['Women', 'Men', 'Unisex']
Length: 3, dtype: str

In [33]:
product_info_clean = product_info.copy()

# Remove full duplicate rows (safe step)
product_info_clean = product_info_clean.drop_duplicates()

# Ensure Product_ID is unique
assert product_info_clean['Product_ID'].duplicated().sum() == 0, "Duplicate Product_ID found!"

# Convert Launch_Date if exists
if 'Launch_Date' in product_info_clean.columns:
    product_info_clean['Launch_Date'] = pd.to_datetime(product_info_clean['Launch_Date'], errors='coerce')

print("Product Info is clean and ready ✅")

Product Info is clean and ready ✅

## WEEKLY_SALES PREPROCESSING

In [34]:
weekly_sales_clean = weekly_sales.copy()
weekly_sales_clean['Week_End_Date'] = pd.to_datetime(weekly_sales_clean['Week_End_Date'], errors='coerce')
weekly_sales_clean.isnull().sum()
weekly_sales_clean.duplicated().sum()
weekly_sales_clean = weekly_sales_clean.drop_duplicates()
weekly_sales_clean.duplicated(subset=['Product_ID', 'Week_End_Date']).sum()
weekly_sales_clean = weekly_sales_clean.drop_duplicates(subset=['Product_ID', 'Week_End_Date'])
weekly_sales_clean = weekly_sales_clean.sort_values(['Product_ID', 'Week_End_Date']).reset_index(drop=True)
weekly_sales_clean.describe()

,Week_End_Date,Qty_Sold,Inventory,On_Order,Returns,Discount
count,2600,2600.000000,2600.000000,2600.000000,2600.000000,2600.000000
mean,2024-01-02 12:00:00,56.454615,397.295769,176.378077,2.305385,9.994231
min,2023-01-07 00:00:00,14.000000,274.000000,50.000000,0.000000,0.000000
25%,2023-07-06 06:00:00,33.000000,347.000000,115.000000,1.000000,5.000000
50%,2024-01-02 12:00:00,53.000000,397.000000,178.000000,2.000000,10.000000
75%,2024-06-30 18:00:00,76.000000,449.000000,239.000000,3.000000,15.000000
max,2024-12-28 00:00:00,150.000000,520.000000,300.000000,11.000000,20.000000
std,NaN,27.501251,60.994836,71.658615,1.740530,7.051313

In [35]:
weekly_sales_clean.columns
numeric_cols = weekly_sales_clean.select_dtypes(include=[np.number]).columns
numeric_cols

Index(['Qty_Sold', 'Inventory', 'On_Order', 'Returns', 'Discount'], dtype='str')

In [36]:
for col in numeric_cols:
    negative_count = (weekly_sales_clean[col] < 0).sum()
    print(f"{col}: {negative_count} negative values")

Qty_Sold: 0 negative values
Inventory: 0 negative values
On_Order: 0 negative values
Returns: 0 negative values
Discount: 0 negative values

In [37]:
weekly_sales_clean['Week_End_Date'].isnull().sum()

np.int64(0)

In [38]:
weekly_sales_clean.groupby('Product_ID')['Week_End_Date'].nunique().describe()

count     25.0
mean     104.0
std        0.0
min      104.0
25%      104.0
50%      104.0
75%      104.0
max      104.0
Name: Week_End_Date, dtype: float64

In [39]:
weekly_sales_clean.groupby('Product_ID')['Week_End_Date'].nunique().value_counts()

Week_End_Date
104    25
Name: count, dtype: int64

In [40]:
print("========== WEEKLY SALES CLEANING SUMMARY ==========")
print("Original Shape:", weekly_sales.shape)
print("Cleaned Shape:", weekly_sales_clean.shape)
print("Duplicate Product-Week Rows:", weekly_sales_clean.duplicated(subset=['Product_ID', 'Week_End_Date']).sum())
print("Missing Values:\n", weekly_sales_clean.isnull().sum())
print("Date Range:", weekly_sales_clean['Week_End_Date'].min(), "to", weekly_sales_clean['Week_End_Date'].max())

========== WEEKLY SALES CLEANING SUMMARY ==========
Original Shape: (2600, 7)
Cleaned Shape: (2600, 7)
Duplicate Product-Week Rows: 0
Missing Values:
 Week_End_Date    0
Product_ID       0
Qty_Sold         0
Inventory        0
On_Order         0
Returns          0
Discount         0
dtype: int64
Date Range: 2023-01-07 00:00:00 to 2024-12-28 00:00:00

In [41]:
print("========== FINAL PREPROCESSING SUMMARY ==========")
print("Product Info Clean Shape:", product_info_clean.shape)
print("Weekly Sales Clean Shape:", weekly_sales_clean.shape)
print("Unique Products in Product Info:", product_info_clean['Product_ID'].nunique())
print("Unique Products in Weekly Sales:", weekly_sales_clean['Product_ID'].nunique())
print("Weekly Sales Date Range:", weekly_sales_clean['Week_End_Date'].min(), "to", weekly_sales_clean['Week_End_Date'].max())

========== FINAL PREPROCESSING SUMMARY ==========
Product Info Clean Shape: (25, 10)
Weekly Sales Clean Shape: (2600, 7)
Unique Products in Product Info: 25
Unique Products in Weekly Sales: 25
Weekly Sales Date Range: 2023-01-07 00:00:00 to 2024-12-28 00:00:00