# Phase 3: Data Preprocessing

This notebook handles the preprocessing of the raw dataset from `data/raw/trail_edge_dataset.xlsx`.

## Objectives
- Load raw data from Excel sheets
- Apply preprocessing functions to clean each dataset
- Validate data quality and handle issues
- Save cleaned datasets to CSV files

## Datasets
1. Product_Information
2. Weekly_Sales  
3. External_Features

## Import Required Libraries

In [8]:
import os
print("Current working directory:", os.getcwd())
print("Files in cwd:", os.listdir('.'))
import sys
print("Python executable:", sys.executable)
print("Python version:", sys.version)

Current working directory: d:\Final Project\notebooks
Files in cwd: ['01_Business_Understanding.ipynb', '02_Data_Understanding.ipynb', '03_Preprocessing.ipynb', '04_EDA.ipynb', '05_Merge_Analysis.ipynb', '06_Demand_Classification.ipynb', '07_Feature_Engineering.ipynb', '08_Model_Training.ipynb', '09_Cross_Validation.ipynb', '10_Forecasting.ipynb', '11_Final_Insights.ipynb']
Python executable: d:\Final Project\venv\Scripts\python.exe
Python version: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]

In [14]:
import sys
sys.path.append('d:/Final Project')
print("Path added: d:/Final Project")
try:
    import src.io
    print("src.io imported successfully")
except ImportError as e:
    print("Import error:", e)

Path added: d:/Final Project
src.io imported successfully

In [15]:
import pandas as pd
import sys
import os

# Add project root to path
sys.path.append('d:/Final Project')

from src.io import load_product_information, load_weekly_sales, load_external_features
from src.preprocess import preprocess_product_info, preprocess_weekly_sales, preprocess_external_features
from src.config import DATA_PROCESSED

print("Imports successful")

Imports successful

## Load Raw Datasets

In [16]:
print("Loading Product_Information...")
df_product_raw = load_product_information()
print(f"Shape: {df_product_raw.shape}")
print(f"Columns: {list(df_product_raw.columns)}")

print("\nLoading Weekly_Sales...")
df_sales_raw = load_weekly_sales()
print(f"Shape: {df_sales_raw.shape}")
print(f"Columns: {list(df_sales_raw.columns)}")

print("\nLoading External_Features...")
df_external_raw = load_external_features()
print(f"Shape: {df_external_raw.shape}")
print(f"Columns: {list(df_external_raw.columns)}")

Loading Product_Information...
Shape: (25, 10)
Columns: ['Product_ID', 'Product_Name', 'Category', 'Sub_Category', 'Gender', 'Color', 'Launch_Season', 'Launch_Date', 'MSRP', 'Wholesale_Price']

Loading Weekly_Sales...
Shape: (2600, 7)
Columns: ['Week_End_Date', 'Product_ID', 'Qty_Sold', 'Inventory', 'On_Order', 'Returns', 'Discount']

Loading External_Features...
Shape: (104, 6)
Columns: ['Week_End_Date', 'Holiday', 'Promo_Event', 'Season', 'Rainfall', 'Avg_Temperature']

## Preprocess Product Information

In [17]:
print("Preprocessing Product_Information...")
print(f"Before: {df_product_raw.shape}")

df_product_clean = preprocess_product_info(df_product_raw)

print(f"After: {df_product_clean.shape}")
print(f"Duplicates removed: {df_product_raw.shape[0] - df_product_clean.shape[0]}")

# Missing values summary
print("\nMissing values:")
print(df_product_clean.isnull().sum())

print("\nFirst few rows:")
df_product_clean.head()

Preprocessing Product_Information...
Before: (25, 10)
After: (25, 10)
Duplicates removed: 0

Missing values:
Product_ID         0
Product_Name       0
Category           0
Sub_Category       0
Gender             0
Color              0
Launch_Season      0
Launch_Date        0
MSRP               0
Wholesale_Price    0
dtype: int64

First few rows:

,Product_ID,Product_Name,Category,Sub_Category,Gender,Color,Launch_Season,Launch_Date,MSRP,Wholesale_Price
0,TE001,Backpack 1,Gear,Backpacks,Women,Blue,Winter,2022-10-19,139,83.21
1,TE002,Backpack 2,Gear,Backpacks,Men,Blue,Spring,2022-01-20,191,114.19
2,TE003,Backpack 3,Gear,Backpacks,Men,Red,Summer,2022-02-21,104,72.57
3,TE004,Pant 4,Apparel,Pants,Unisex,Green,Spring,2022-12-22,149,102.90
4,TE005,Accessorie 5,Gear,Accessories,Women,Green,Spring,2022-04-15,59,37.76

### Insights: Product_Information
- Dataset shape changed from X to Y rows
- Z duplicate rows were removed
- Missing values in columns: [list if any]
- Data types validated and converted appropriately

## Preprocess Weekly Sales

In [18]:
print("Preprocessing Weekly_Sales...")
print(f"Before: {df_sales_raw.shape}")

df_sales_clean = preprocess_weekly_sales(df_sales_raw)

print(f"After: {df_sales_clean.shape}")
print(f"Duplicates removed: {df_sales_raw.shape[0] - df_sales_clean.shape[0]}")

# Check uniqueness
unique_combinations = df_sales_clean.groupby(['Product_ID', 'Week_End_Date']).size()
duplicate_combos = (unique_combinations > 1).sum()
print(f"Duplicate Product_ID + Week_End_Date combinations: {duplicate_combos}")

# Missing values summary
print("\nMissing values:")
print(df_sales_clean.isnull().sum())

print("\nFirst few rows:")
df_sales_clean.head()

Preprocessing Weekly_Sales...
Before: (2600, 7)
After: (2600, 7)
Duplicates removed: 0
Duplicate Product_ID + Week_End_Date combinations: 0

Missing values:
Week_End_Date    0
Product_ID       0
Qty_Sold         0
Inventory        0
On_Order         0
Returns          0
Discount         0
dtype: int64

First few rows:

  Week_End_Date Product_ID  Qty_Sold  Inventory  On_Order  Returns  Discount
0    2023-01-07      TE001        69        504       129        3        20
1    2023-01-14      TE001        73        509       240        2        10
2    2023-01-21      TE001        61        492       189        4         5
3    2023-01-28      TE001        51        483        80        3         5
4    2023-02-04      TE001        69        495       195        2        15

### Insights: Weekly_Sales
- Dataset shape changed from X to Y rows
- Z duplicate rows were removed
- Ensured uniqueness of Product_ID + Week_End_Date combinations
- Data sorted by Product_ID and Week_End_Date
- Missing values in columns: [list if any]

## Preprocess External Features

In [19]:
print("Preprocessing External_Features...")
print(f"Before: {df_external_raw.shape}")

df_external_clean = preprocess_external_features(df_external_raw)

print(f"After: {df_external_clean.shape}")
print(f"Duplicates removed: {df_external_raw.shape[0] - df_external_clean.shape[0]}")

# Missing values summary
print("\nMissing values:")
print(df_external_clean.isnull().sum())

print("\nFirst few rows:")
df_external_clean.head()

Preprocessing External_Features...
Before: (104, 6)
After: (104, 6)
Duplicates removed: 0

Missing values:
Week_End_Date      0
Holiday            0
Promo_Event        0
Season             0
Rainfall           0
Avg_Temperature    0
dtype: int64

First few rows:

  Week_End_Date  Holiday  Promo_Event  Season  Rainfall  Avg_Temperature
0    2023-01-07        1            1  Winter     15.30            11.04
1    2023-01-14        0            0  Winter     10.24            16.52
2    2023-01-21        0            0  Winter      7.17            15.64
3    2023-01-28        0            0  Winter     39.20            19.58
4    2023-02-04        0            0    Fall      5.54            18.50

### Insights: External_Features
- Dataset shape changed from X to Y rows
- Z duplicate rows were removed
- Season text standardized to title case
- Data sorted by Week_End_Date
- Missing values in columns: [list if any]

## Save Cleaned Datasets

In [20]:
# Save to CSV files
output_dir = DATA_PROCESSED
output_dir.mkdir(parents=True, exist_ok=True)

df_product_clean.to_csv(output_dir / 'product_info_clean.csv', index=False)
df_sales_clean.to_csv(output_dir / 'weekly_sales_clean.csv', index=False)
df_external_clean.to_csv(output_dir / 'external_features_clean.csv', index=False)

print("Cleaned datasets saved successfully:")
print("- product_info_clean.csv")
print("- weekly_sales_clean.csv") 
print("- external_features_clean.csv")

Cleaned datasets saved successfully:
- product_info_clean.csv
- weekly_sales_clean.csv
- external_features_clean.csv

## Preprocessing Summary

In [21]:
print("\n=== PREPROCESSING SUMMARY ===")
print(f"\nProduct_Information:")
print(f"  Raw rows: {df_product_raw.shape[0]}, Cleaned rows: {df_product_clean.shape[0]}")
print(f"  Columns: {df_product_clean.shape[1]}")
print(f"\nWeekly_Sales:")
print(f"  Raw rows: {df_sales_raw.shape[0]}, Cleaned rows: {df_sales_clean.shape[0]}")
print(f"  Columns: {df_sales_clean.shape[1]}")
print(f"\nExternal_Features:")
print(f"  Raw rows: {df_external_raw.shape[0]}, Cleaned rows: {df_external_clean.shape[0]}")
print(f"  Columns: {df_external_clean.shape[1]}")
print(f"\nAll cleaned datasets have been saved to data/processed/")

=== PREPROCESSING SUMMARY ===

Product_Information:
  Raw rows: 25, Cleaned rows: 25
  Columns: 10

Weekly_Sales:
  Raw rows: 2600, Cleaned rows: 2600
  Columns: 7

External_Features:
  Raw rows: 104, Cleaned rows: 104
  Columns: 6

All cleaned datasets have been saved to data/processed/